# Travis CI integration -- https://travis-ci.org/troglobit/libite
# Defaults to GNU GCC and autotools: ./configure && make && make test
language: c

# Use docker for quicker builds, it now allows https://docs.travis-ci.com/user/apt/
sudo: false

# Test build with both GCC and Clang (LLVM)
compiler:
  - gcc
  - clang

script:
  - ./autogen.sh
  - ./configure --prefix=/tmp --disable-silent-rules
  - make clean
  - make -j5
  - make install-strip
  - ls -lR /tmp
  - make check
